Spruce up the README
enarx/bot-test pull request #3
Opened 2020-08-12 19:34 UTC by mbestavros

2020-08-12 19:38 UTC, npmccallum commented
This is a comment to see how events work. Note that this PR is not mergeable.

2020-08-12 19:45 UTC, npmccallum requested changes
This needs changes.

2020-08-12 19:47 UTC, mbestavros commented on README.md
> +A test repository for the Enarxbot.
This is a code quote.

2020-08-12 20:06 UTC, npmccallum requested changes
Reject a second time.

2020-08-12 20:10 UTC, npmccallum requested changes
A bucket full of denials!

2020-08-12 20:54 UTC, npmccallum requested changes
Run actions again.

2020-08-18 19:00 UTC, mbestavros commented
It may be helpful to leave this open for GraphQL testing. I'm not closing this for the moment.

2020-09-24 18:37 UTC, closed without merging